### ISSUE TITLE
Run parallel benchmarks

### ISSUE THREAD

**Issue by veronia-iskandar** [eugene-tarassov/vivado-risc-v#102]
Hello,

Thank you very much for providing this implementation. I was wondering if I can run a benchmark (e.g matrix multiplication) on the cores? Also, can I use the existing Linux to parallelize the benchmark over several cores?

Thanks!

**Comment by eugene-tarassov** [comment]
Sure, you can run parallel benchmarks on Linux.
This repo contains everything necessary to run any kind of Linux benchmarks over several cores.
