### ISSUE TITLE
Remove ethernet block from list of top level IOs

### ISSUE THREAD

**Issue by yswntht** [eugene-tarassov/vivado-risc-v#105]
Hi,

Is there any flag that i can use to remove Ethernet block from list of top level IOs? Just uart, sdcard would be sufficient for my purpose. I can try edit top-file manually but want to check with you if there is an automated way?

Thanks.

**Comment by mwrnd** [comment]
There is currently no way to do this with a flag.

You will need to edit the `vivado-risc-v/board/YOURBOARNAME/riscv-202?.?.tcl` file for your board/Vivado_Version.

Compile only the `vivado-tcl` portion of your board's base design.
```
cd vivado-risc-v
source /tools/Xilinx/Vivado/2021.2/settings64.sh
make  CONFIG=rocket64b2  BOARD=YOURBOARNAME  vivado-tcl
```

[Source](https://docs.xilinx.com/r/en-US/ug939-vivado-designing-with-ip-tutorial/Source-the-Tcl-Script?tocId=jFIwPQ0k2AQihKXYcPCJcA) the `.tcl` file that you end up with under `vivado-risc-v/workspace/rocket64b2/system-YOURBOARNAME.tcl` into Vivado.

Make any necessary changes to the block design in Vivado then run `write_bd_tcl  NEW_riscv-202x.x.tcl` in Vivado's Tcl Console. Manually copy the contents of this file into the appropriate `vivado-risc-v/board/YOURBOARNAME` file and run a full bitstream compile of your updated design.
```
make  CONFIG=rocket64b2  BOARD=YOURBOARNAME  bitstream
```

[This thread](https://github.com/eugene-tarassov/vivado-risc-v/discussions/104#discussioncomment-3589170) and [this page](https://github.com/mwrnd/innova2_experiments/tree/main/riscv_rocket64b4l2w_xdma#recreating-the-risc-v-design) may be useful references.
