### ISSUE TITLE
KC705 - Wont boot without initiated UART Connection. 

### ISSUE THREAD

**Issue by russeree** [eugene-tarassov/vivado-risc-v#108]
Currently working with the KC705 platform and unless I open a serial connection OpenSBI will not execute. Is there any way to bypass this? Would earlycon have anything to do with this?

My setup ideally is just an SSH connection. 

Thanks in advance.

**Comment by eugene-tarassov** [comment]
KC705 design implements RS232 hardware flow control.
It waits until serial port is ready to make sure no characters are lost.
You can disable this by disconnecting UART CTSn (Clear To Send) signal and connecting it to logic '0'.

**Comment by russeree** [comment]
Thanks for the quick response. Will test this evening and update with results.
