### ISSUE TITLE
Gemmini running issue ?

### ISSUE THREAD

**Issue by ConstantPark** [eugene-tarassov/vivado-risc-v#11]
Hello. I am working on running the Gemmini accelerator using the uploaded material.
(Gemminis SW in their github and my device is vc707 rev1.1)
The DNN code in Gemmini git is compiled and executed.
But when the part corresponding to the accelerator is executed, the device stops. 
(Gemmni's linux softwares such as matmul)

Do you have any experience with this?

**Comment by eugene-tarassov** [comment]
No, I don't have any experience with the Gemmini software.

**Comment by gnodipac886** [comment]
@ConstantPark could you share how you were able to deploy gemmini on VC707?
