### ISSUE TITLE
build /u-boot/arch/riscv/cpu/start.o failed in ubuntu18.04

### ISSUE THREAD

**Issue by Yuxin-Yu** [eugene-tarassov/vivado-risc-v#113]
Hello, I used the latest project, and the execution error was reported in Ubuntu18.04
<img width="707" alt="屏幕截图 2022-09-27 112328" src="https://user-images.githubusercontent.com/38584421/192427026-1ffddee6-b7d3-4062-858a-1e46d33daa1b.png">
Do you known how can I fix it ?

**Comment by eugene-tarassov** [comment]
It works fine for me with Ubuntu 20.04.5 LTS.

**Comment by Yuxin-Yu** [comment]
> This error is related to SSL library version. You, probably, just need to update your system with latest packages.
Thank you sir.But sometime when I execute "./mk-sd-image",there are  another error
<img width="584" alt="屏幕截图 2022-09-29 093536" src="https://user-images.githubusercontent.com/38584421/192918885-73bfad92-49dc-42f5-a041-958982b4db7a.png">
How Can fix it,thanks

**Comment by Yuxin-Yu** [comment]
I have solved this tag error.It is related to linux-stable version
