### ISSUE TITLE
PLL clock setting

### ISSUE THREAD

**Issue by JackChenggg** [eugene-tarassov/vivado-risc-v#116]
If I change the PLL settings, such as adding a clock, do I need to change the device tree settings?

**Comment by eugene-tarassov** [comment]
No, you don't need to change the device tree after adding a clock.
Unless you plan to add a device driver that needs info about that clock in the device tree.

**Comment by JackChenggg** [comment]
If "video test pattern generator" is used
Device tree needs to give "clocks" information
I added clk_out5 to the PLL,
What information do I need to add to the device tree?
![image](https://user-images.githubusercontent.com/116940909/198831084-ce3afe23-9859-4522-9f4f-2c539d447215.png)
![image](https://user-images.githubusercontent.com/116940909/198831104-c75e7910-bb7b-48ec-b408-ec695af86c3a.png)

**Comment by eugene-tarassov** [comment]
Yes, for TPG driver you need to define a clock in the board bootrom.dts.
Refer to the clock provider schema: [clock.yaml](https://github.com/devicetree-org/dt-schema/blob/main/dtschema/schemas/clock/clock.yaml)

Something like:
```
	clocks {
		#address-cells = <1>;
		#size-cells = <1>;
		ranges;

		clk_out5: clk5 {
			compatible = "fixed-clock";
			#clock-cells = <0>;
			clock-frequency = <250000000>;
		};
	}
```
Then use it like:
```
    clocks = <&clk_out5 0>;
```
