### ISSUE TITLE
makefile boom source directory

### ISSUE THREAD

**Issue by Shuiliusheng** [eugene-tarassov/vivado-risc-v#12]
CHISEL_SRC := $(foreach path, src/main rocket-chip/src/main riscv-boom/src/main, $(shell test -d $(path) && find $(path) -iname "*.scala"))
Do  I need to modify "riscv-boom/src/main" to "generators/riscv-boom/src/main"?
Thank you.

**Comment by eugene-tarassov** [comment]
Normally, this line is not needed. It is only useful if you want to checkout different version of riscv-boom and do incremental rebuild of the project. But it is better to run a clean build in such case.  I will commit a fix anyway.

**Comment by eugene-tarassov** [comment]
I have updated the Makefile
