### ISSUE TITLE
Bare Metal and Linux on arty-a7-100t

### ISSUE THREAD

**Issue by Nitheesh1609** [eugene-tarassov/vivado-risc-v#120]
Hi, 
I am trying to replicate the repo on an ARTY-A7-100T board.
I ran make CONFIG=rocket64b1 BOARD=arty-a7-100t flash. and it has completed succesfully.
**
<img width="886" alt="image" src="https://user-images.githubusercontent.com/68940726/205512672-6ec313e2-658b-457b-9ddc-64c584dea640.png">
**
Then I tried to run xsdb to download the baremetal boot.elf and check the system. But I do not find any RISC-V on it.
<img width="193" alt="image" src="https://user-images.githubusercontent.com/68940726/205512759-e58d6cf5-9002-49c1-9774-91eda1aab3ea.png">

Am I missing something?

**Comment by eugene-tarassov** [comment]
Have you pressed the PROG button on the board to load new bitstream into FPGA?

**Comment by Nitheesh1609** [comment]
Thanks, I was able to run the bare-metal in the hello world in the UART terminal.
When I try to use the ./mk-sd-card script, I get a sfdisk cannot open error, even when I add have my SD-card connected.
![image](https://user-images.githubusercontent.com/68940726/205672858-e7bbc88f-a334-42bb-85eb-8cfde1ceeb83.png)

**Comment by eugene-tarassov** [comment]
The disk is mounted. It must not be mounted for the script to work. Try `sudo umount /dev/sde`

**Comment by Nitheesh1609** [comment]
/dev/sde was unmounted but for some reason /dev/sde1 and /dev/sde2 were mounted. I was able to build the sd card image and make the sd card.
But Now when I try to boot linux on it,
![image](https://user-images.githubusercontent.com/68940726/205981994-39606e92-7dff-4048-9af7-f80ffea5a1e8.png)
I get this unable to access timeout error when booted.

**Comment by eugene-tarassov** [comment]
Check your SD card connection, it should look like this:
![arty-a7-100t](https://user-images.githubusercontent.com/61023337/206007889-fdc61a3d-6615-4b73-a170-bd9fbfdd225b.png)

Also, at the moment, we are having problems with Debian Linux taking too long time to boot on a slow designs like Arty A7. You will probably need to change Linux timeouts, see [this comment](https://github.com/eugene-tarassov/vivado-risc-v/issues/119#issuecomment-1337976249)

**Comment by Nitheesh1609** [comment]
Yes, when I changed my PmodSD from JA to JB I was able to rub the linux. Yeah It took a long time to boot up. I have a minimal linux kernel (Linux with busybox) a boot.elf file with the bzImage, a initrd and a rootfs.cpio.gz file. Can I directly have a SD card with the boot.elf, from which the linux can boot up or do we need to make any changes in the uboot or anyother to get to boot from my custom boot.elf ?

**Comment by eugene-tarassov** [comment]
> I have a minimal linux kernel (Linux with busybox)  a boot.elf file with the bzImage

I'm not sure what you mean. The normal way to boot Linux on RISC-V is to run Supervisor Binary Interface (e.g. OpenSBI), which includes u-boot, then u-boot loads initrd and the kernel image. OpenSBI, u-boot and the kernel need to be patched to include drivers from this repo for UART, SD and Ethernet. mk-sd-card does all that patching, adds initrd and rootfs, and creates bootable SD card.

**Comment by Nitheesh1609** [comment]
https://github.com/cnrv/fpga-rocket-chip
I am trying to replicate that idea but had a block in linux or risc-v processor not booting up. Following the linux image generation steps, I built a bootable elf file, I wanted to know If I use that elf file in this repo?

**Comment by eugene-tarassov** [comment]
> I built a bootable elf file, I wanted to know If I use that elf file in this repo?

No, you cannot use bootable elf file from that repo - the hardware design, peripherals are not same.

But you can use different initrd and rootfs: build it yourself with busybox, or use other Linux distribution instead of Debian, like Ubuntu or whatever.

**Comment by Nitheesh1609** [comment]
Sure will try that!
