### ISSUE TITLE
Kria KV260 support

### ISSUE THREAD

**Issue by Chamusuke** [eugene-tarassov/vivado-risc-v#124]
Hellow, I find your posts very helpful.
I have a KV260.
I want to run Debian on RISC-V on Zynq PL, not on an ARM CPU on a Zynq PS.
Is there any advice and convenient way?

**Comment by mwrnd** [comment]
I too am working on a [similar project](https://github.com/mwrnd/innova2_experiments/tree/main/riscv_rocket64b4l2w_xdma). I want to run a RISC-V system entirely in Programmable Logic and memory. I use PCIe-to-AXI ([XDMA](https://docs.xilinx.com/r/en-US/pg195-pcie-dma/Introduction)) and the Zynq equivalent would be [AXI HPM](https://xilinx.github.io/Embedded-Design-Tutorials/docs/2021.2/build/html/docs/Introduction/ZynqMPSoC-EDT/7-design1-using-gpio-timer-interrupts.html).

A RISC-V system requires five "external" interfaces; RAM, storage, UART, Ethernet, and JTAG. My idea would be to use the Zynq to translate the various protocols for the RISC-V and host it. Replace *XDMA* with *Zynq* and *PCIe* with *Keyboard+Mouse+Video* in the following diagram.

![RISC-V System Overview](https://user-images.githubusercontent.com/38073881/211031043-8df749bb-7809-4e40-89d2-8993f3ab0db1.png)

RAM and storage can be combined by using [tmpfs](https://docs.kernel.org/filesystems/tmpfs.html) as a boot drive similar to  [Live](https://help.ubuntu.com/community/LiveCD) Linux systems.  The KV260 shares memory between the [PS and PL](https://docs.xilinx.com/r/en-US/ds987-k26-som/Functional-Overview-and-Block-Diagram) so the 4GB would need to be divided up among the Zynq, RISC-V, and RISC-V storage. Note [debian-riscv64.sd.img.gz](https://github.com/eugene-tarassov/vivado-risc-v/releases/tag/v3.4.0) extracts into a 1.6GB file.

The [UART](https://github.com/mwrnd/innova2_experiments/tree/main/xdma_uart-to-uart) and Ethernet would then need to be tunneled. The [Xilinx Virtual Cable](https://docs.xilinx.com/r/en-US/pg213-pcie4-ultrascale-plus/XVC-over-PCIe-Through-AXI-AXI-XVC) should allow JTAG over AXI.

I am stuck on 
1) boot a combined RAM+storage Linux image (Live RISC-V System)
2) [OpenOCD](https://openocd.org/doc/html/Debug-Adapter-Configuration.html) `xlnx_pcie_xvc` to `xsdb` communication
3) Ethernet Tunnel
