### ISSUE TITLE
Could we run 32-bit bare-metal on `rocket32sxx`? 

### ISSUE THREAD

**Issue by cnSchwarzer** [eugene-tarassov/vivado-risc-v#125]
Hi, it is possible to run 32bit bare-metal on rocket32sxx?

Is it possible to generate a 32bit bootrom?

And what about run multiple bare-metal on separate cores?

**Comment by eugene-tarassov** [comment]
> Hi, it is possible to run 32bit bare-metal on rocket32sxx?

Yes. The "hello word" example can be built to run on rocket32sxx.
For details, see use of CROSS_COMPILE_NO_OS_TOOLS in the project [Makefile](https://github.com/eugene-tarassov/vivado-risc-v/blob/master/Makefile#L165).

> Is it possible to generate a 32bit bootrom?

Yes. 32bit bootrom is generated for rocket32sxx configs.

> And what about run multiple bare-metal on separate cores?

It is up to a software on the first core to start other cores.
It is done by sending interrupt request to another core.

**Comment by cnSchwarzer** [comment]
Thanks!
