### ISSUE TITLE
Custom Instructions

### ISSUE THREAD

**Issue by cnSchwarzer** [eugene-tarassov/vivado-risc-v#128]
Hi, sorry to bother you!

I'm very new to RISCV, and I want to add my custom instructions to this project, and I found RocketChip has something useful: https://github.com/chipsalliance/rocket-chip/blob/master/src/main/scala/scie/SCIE.scala . Is it possible to modify this file in the middle of make, or should I specify a fork of the whole rocket-chip design with my own modification?

I also learned something named RoCC, is that the same as `Gemmini accelerator`? How do I modify the Makefile to add a custom RoCC to the design?

I don't know how to easily integrate to this project, and make everything work, do you have related suggestions?

Thank you!

**Comment by eugene-tarassov** [comment]
I think the best way is to create a new repo and include this repo as submodule. In your repo, you can add your own Scala files to extend RocketChip functionality, setup [SBT](https://www.scala-sbt.org/) project, add Makefile, etc. You should not need to modify anything in the submodule, you can just refer to it from SBT and Makefile.

> I also learned something named RoCC, is that the same as Gemmini accelerator? 

RoCC is RocketChip interface for adding processor extensions, Gemmini  is an example of such extension that uses RoCC.

**Comment by cnSchwarzer** [comment]
Thanks, I'll try figure it out

**Comment by cnSchwarzer** [comment]
Does this sound right?
- Make your repo as a submodule
- Create my own top scala file just like your `/src/main/scala/rocket.scala`, but define class of my own. For example extend one of Rocket32s1/Rocket64b2/etc..
- Create my custom RoCC, and build and new it in scala config
- Create Makefile that control over this repo

**Comment by eugene-tarassov** [comment]
Yes.

One more thing: Scala is built by SBT (Scala Build Tool), so you will need SBT config files: `build.sbt`, `project/build.properties` and `project/plugins.sbt`.

**Comment by cnSchwarzer** [comment]
Thank you very much
