### ISSUE TITLE
u-boot compile error

### ISSUE THREAD

**Issue by Shuiliusheng** [eugene-tarassov/vivado-risc-v#13]
when i use my riscv-linux- toolchain to compile u-boot, there is one error, "arch/riscv/cpu/mtrap.S:67: error: Instruction csrr requires absolute expression". Could you give me some advice, thank you.

**Comment by eugene-tarassov** [comment]
I recommend to use Ubuntu 20.04.1 LTS and the Makefile from this repo to install riscv toolchain and build u-boot. It works fine for me.
