### ISSUE TITLE
how to use my own board？

### ISSUE THREAD

**Issue by certic1** [eugene-tarassov/vivado-risc-v#141]
Now I want to use zcu104 to apply this. I generate the vivado project via the board it provides such as kc705, and in this project i modify the chip into zcu104.I want to change the block design and then generate the bitstream i want.But in the blcok design, when i change ddr3 into ddr4 some pins can't connect to  mem_reset_control,and there are also some errors about clk_domain and freq_hz. I want to know whether the directtion is right and how can i fix the pin errors?

**Comment by eugene-tarassov** [comment]
To add support for a board, you need to create a subdirectory under `board` directory, similar to subdirectories for other boards. This is expert level task, I cannot provide step-by-step instructions, the process is rather complicated and depends on the board capabilities.
