### ISSUE TITLE
Build for arty-a7-100T board : Stuck on creating bitstream

### ISSUE THREAD

**Issue by keitaiazuma33** [eugene-tarassov/vivado-risc-v#143]
Hi,

I'm trying to implement a RISC-V core on arty-at-100t board and am having trouble creating a bitstream (Vivado 2022.2 / Ubuntu 2204.1.8.0).
（My goal is to edit (add custom instructions) and implement my own RISC-V core on arty-a7-100t board and not to run a linux system on this FPGA）

I have followed through the README and the process seems to have successfully run up to "make update-submodules",
though the "make CONFIG=rocket64b1 BOARD=arty-a7-100t bitstream" gives me numbers of warnings.

Some of the warnings returned are as follows; 
(There are over 100 warnings like these while running the above command)
・[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
・[warn] /mnt/c/Users/username/desktop/vivado-risc-v/rocket-chip/src/main/scala/tilelink/Bundles.scala:163:14: Unable to determine primary constructor!
-> [warn] sealed trait TLChannel extends TLBundleBase {
・[warn] /mnt/c/Users/username/desktop/vivado-risc-v/generators/gemmini/src/main/scala/gemmini/Normalizer.scala:530:40: method fire in class AddMethodsToReadyValid is deprecated (since Chisel 3.5): Calling this function with an empty argument list is invalid in Scala 3. Use the form without parentheses instead
-> [warn]       next_state := Mux(reciprocal_out.fire(), idle, state)

Will these warnings be resolved if I use the released version(4.3.0) instead of cloning the github repo? If so, how may I use the released version to open a Vivado project?

It would be greatly appreciated if anyone could help me creating a bitstream (and opening a Vivado project) for arty-a7-100t  board.

Kind regards,
Kevin

**Comment by eugene-tarassov** [comment]
Chisel and Scala warnings come from RocketChip or Gemmini submodules, which are included by reference, they are not part of this repo. I have not seen a version of submodules which would build without warnings. I believe these warnings can be safely ignored. All submodule versions referenced by this repo are verified to build without errors and pass all tests.

> Will these warnings be resolved if I use the released version(4.3.0) instead of cloning the github repo?

No.
