### ISSUE TITLE
Run bare metal with 32bits "rocket32s1"

### ISSUE THREAD

**Issue by joeljeanmonod-rgb** [eugene-tarassov/vivado-risc-v#146]
Hi,

It said on the bare metal page that it can run 64bit programm from the sd card.

My question is : Can i run 32bits bare metal programm with the rocket 32 bits core from the sd card ?

**Comment by eugene-tarassov** [comment]
Yes.
Use 32-bit compiler to build the program:
```
cd bare-metal/hello-world
make CROSS_COMPILE=../../workspace/gcc/riscv/bin/riscv32-unknown-elf- CFLAGS='-march=rv32imac -mabi=ilp32' clean all
```

**Comment by joeljeanmonod-rgb** [comment]
thank you
