### ISSUE TITLE
OpenOCD not working on Nexys Video

### ISSUE THREAD

**Issue by tirumalnaidu** [eugene-tarassov/vivado-risc-v#15]
When I try to run the openocd, i face the following error:

    tirumal@ACER-SWIFT-3:~$ sudo $(which openocd) -f ./openocd.cfg 
    Open On-Chip Debugger 0.11.0-rc2+dev-01538-gd57ab0b63 (2021-03-01-19:50)
    Licensed under GNU GPL v2
    For bug reports, read
	    http://openocd.org/doc/doxygen/bugs.html
    DEPRECATED! use 'adapter speed' not 'adapter_khz'
    DEPRECATED! use 'adapter driver' not 'interface'
    Info : auto-selecting first available session transport "jtag". To override use 'transport select <transport>'.
    Info : Nested Tap based Bscan Tunnel Selected
    Info : Listening on port 6666 for tcl connections
    Info : Listening on port 4444 for telnet connections
    Error: no device found
    Error: unable to open ftdi device with vid 0403, pid 6014, description '*', serial '*' at bus location '*'

My openocd.cfg file:

      adapter_khz 20000
      interface ftdi
      ftdi_vid_pid 0x0403 0x6014
      ftdi_layout_init 0x00e8 0x60eb
      ftdi_tdo_sample_edge falling
      reset_config none
      set _CHIPNAME riscv
      jtag newtap $_CHIPNAME cpu -irlen 6
      set _TARGETNAME $_CHIPNAME.cpu
      target create $_TARGETNAME.0 riscv -chain-position $_TARGETNAME
      $_TARGETNAME.0 configure -work-area-phys 0x80000000 -work-area-size 10000 -work-area-backup 1
      riscv use_bscan_tunnel 5

**Comment by eugene-tarassov** [comment]
The project is setup for Xilinx tools.
It should be possible to modify it to work with OpenOCD.
I'm not sure how to do it, if you figure it out - please let me know.

Instead, you can just use Xilinx debugger:
```
$ xsdb

****** Xilinx System Debugger (XSDB) v2020.2
  **** Build date : Nov 18 2020-10:01:48
    ** Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.

xsdb% connect
xsdb% targets
  1  xc7a200t
xsdb% targets 1
xsdb% fpga workspace/rocket64b2/vivado-nexys-video-riscv/nexys-video-riscv.runs/impl_1/riscv_wrapper.bit
xsdb% targets
  1*  xc7a200t
     2  RISC-V
        3  Hart #0 (Running)
        4  Hart #1 (Running)
xsdb% targets 3
xsdb% stop
xsdb% Info: Hart #0 (target 3) Stopped at 0x8000000c (Suspended)
xsdb% rrd
zero: 0000000000000000    ra: 0000000000011b20    sp: 000000008000ff40
  gp: 0000000000000000    tp: 0000000000000000    t0: 800000000094112d
  t1: 0000000080010000    t2: 000000008ff10000    s0: 0000000000000000
  s1: 0000000080000018    a0: 0000000000000000    a1: 0000000000010080
  a2: 0000000000000000    a3: 0000000000000001    a4: 0000000000000001
  a5: 0000000080000008    a6: 0000000000000000    a7: 000000000ff00000
  s2: 0000000000000000    s3: 0000000080010000    s4: 000000007fffffff
  s5: 0000000080000030    s6: 0000000000000000    s7: 0000000000000002
  s8: 0000000000000070    s9: 0000000000000038   s10: 0000000000000040
 s11: 0000000000000000    t3: ddb92550705603ea    t4: 0000000000000000
  t5: 0000000000000000    t6: 0000000000000000    pc: 000000008000000c
  fp                     csr

xsdb%
```
