### ISSUE TITLE
Cycle hardware counter

### ISSUE THREAD

**Issue by mbelda** [eugene-tarassov/vivado-risc-v#161]
Hello,

Is there any special config that must be specified on the design to enable the cycle hardware counter?
I find that in the provided riscv-vc707 bitstream cycles are read correctly but on my designs (Rocket64b2 as it is in `rocket.scala`) I can't read cycles.

**Comment by eugene-tarassov** [comment]
The provided riscv-vc707 bitstream is built using Rocket64b2 config from rocket.scala and Vivado 2021.1. There should be no difference.

**Comment by mbelda** [comment]
The lecture is not right in any architecture. Probably because of what it is said on Issue https://github.com/eugene-tarassov/vivado-risc-v/issues/163. 
Maybe we can change to that issue and close this.
