### ISSUE TITLE
The frequency of rocketx1 with genesys2

### ISSUE THREAD

**Issue by Shuiliusheng** [eugene-tarassov/vivado-risc-v#18]
Hello, how can I find out the frequency of the cpu written to the fpga after the vivado synthesis? I used the config "rocket64x1" and genesys2 board. Thank you.

**Comment by eugene-tarassov** [comment]
Open the project in Vivado - the project file is workspace/rocket64x1/vivado-genesys2-riscv/genesys2-riscv.xpr.
Click Open Block Design, double click Clocking Wizard, you will see all clocking settings.
Output Clocks / clk_out1 is the CPU clock.

Default frequencies are stored in [board/rocket-freq](https://github.com/eugene-tarassov/vivado-risc-v/blob/master/board/rocket-freq) file - it is used to create Vivado projects.
