### ISSUE TITLE
Some signals used before declaration (axi_sdc)

### ISSUE THREAD

**Issue by Dofingert** [eugene-tarassov/vivado-risc-v#195]
`wire [31:0] m_bus_dat_i` declared in [axi_sdc_controller.v-L466](https://github.com/eugene-tarassov/vivado-risc-v/blob/729bd7726dad097405ac582da09442efe99b8351/sdc/axi_sdc_controller.v#L466C1-L466C25)

but used in [axi_sdc_controller.v-L429](https://github.com/eugene-tarassov/vivado-risc-v/blob/729bd7726dad097405ac582da09442efe99b8351/sdc/axi_sdc_controller.v#L429)

`reg [2:0] m_axi_bresp_cnt` has the same issue.

**Comment by eugene-tarassov** [comment]
Fixed.
Thanks!
