### ISSUE TITLE
gcc inside debian img

### ISSUE THREAD

**Issue by elialaz** [eugene-tarassov/vivado-risc-v#216]
Hi Eugene,

i have a quick question and I'm not entirely sure about the answer, how can I install inside the linux partition a gcc compiler? 
unfortunately i don't have an internet connection on the board so i have to load it from my main system mounting the partition by hand (x86 system)

**Comment by EternitYjl** [comment]
Hello, I meet the same problems. My board has either no ethernet. I also need gcc(riscv64) compiler. So how did you solve this problem or do you have any suggestion?
