### ISSUE TITLE
Question about the bootrom generation

### ISSUE THREAD

**Issue by cassebas** [eugene-tarassov/vivado-risc-v#225]
Hi Eugene,
I'd like to do some experiments with the bootrom. Currently the only way I know of on how to do this, is to make changes to the bootrom code and generate a whole new bitstream. This takes a lot of time, could there be another way to replace the bootrom without having to generate the complete bitstream?
Thnx!

**Comment by eugene-tarassov** [comment]
No, with current design there is no other way to make changes to the bootrom code.
