### ISSUE TITLE
Large size of memory

### ISSUE THREAD

**Issue by haipnh** [eugene-tarassov/vivado-risc-v#244]
Hi,

In the `Makefile.inc`, when I increase the `MEMORY_SIZE` from `0x40000000` -> `0x100000000`, it will parse the wrong value to the `bootrom/system.dts`.

It is changed from
```
mkdir -p workspace/rocket64b1/system-zcu104
cat workspace/rocket64b1/system.dts board/zcu104/bootrom.dts >bootrom/system.dts
sed -i "s#reg = <0x80000000 *0x.*>#reg = <0x80000000 0x40000000>#g" bootrom/system.dts
sed -i "s#reg = <0x0 0x80000000 *0x.*>#reg = <0x0 0x80000000 0x0 0x40000000>#g" bootrom/system.dts
```

To
```
mkdir -p workspace/rocket64b1/system-zcu104
cat workspace/rocket64b1/system.dts board/zcu104/bootrom.dts >bootrom/system.dts
sed -i "s#reg = <0x80000000 *0x.*>#reg = <0x80000000 0x80000000>#g" bootrom/system.dts
sed -i "s#reg = <0x0 0x80000000 *0x.*>#reg = <0x0 0x80000000 0x1 0x0>#g" bootrom/system.dts
```

It can still successfully write a bitstream. But there isn't `HART #0`, only `RISC-V JTAG DTM (Debug Transport Module is held in reset)` instead. The reset signal is correct as shown in issue #107.

I revert the change to `0x40000000`, it's fine.

**Comment by eugene-tarassov** [comment]
The bootrom/system.dts values look good to me. Most likely the problem is caused by misconfigured DDR controller in your zcu104 design.

**Comment by haipnh** [comment]
You're right. The bootrom is fine. The problem seems from the misconfiguration of the custom memory part in Vivado.
