### ISSUE TITLE
Other FPGAs

### ISSUE THREAD

**Issue by Ammadali90** [eugene-tarassov/vivado-risc-v#28]
Is it possible to use these implementations of ZCU102?
if yes, then what are the changes required to make it run.

Thanks in advance!

**Comment by eugene-tarassov** [comment]
It is possible, but it is Zynq board. The large portion of the chip is taken by ARM CPU, which is not needed for RISC-V emulation.
As result, FPGA is rather small, 274K LUTs - not enough to work with large designs like BOOM or Gemmini. Using pure FPGA board allows much cleaner and more powerful RISC-V implementations.

> if yes, then what are the changes required to make it run

The board specific files are in the `board` directory. They will need changes/additions to add support for ZCU102. I cannot tell exact changes - it is not a simple task.

**Comment by Ammadali90** [comment]
Thanks for your reply!

**Comment by xiongwu12345** [comment]
> As result, FPGA is rather small, 274K LUTs - not enough to work with large designs like BOOM or Gemmini.

But I find that there are 600K LUTs on the website.

![image](https://user-images.githubusercontent.com/43496629/131854112-14f44058-b745-410b-bac0-5e9f29eb0cca.png)

**Comment by eugene-tarassov** [comment]
System Logic Cells are not same as LUTs (Look Up Tables). FPGAs consist of LUTs, while System Cells is a common measure of ASIC design complexity. Xilinx marketing uses some rather arbitrary multiplier to convert actual LUT count to some abstract System Logic Cells number. You can find the real LUT count in the Zynq UltraScale+ MPSoC Data Sheet.

**Comment by xiongwu12345** [comment]
Yes, I see. Thanks.
