### ISSUE TITLE
32bits OS support

### ISSUE THREAD

**Issue by Shuiliusheng** [eugene-tarassov/vivado-risc-v#32]
Hi, besides changing the riscv toolchain, what else needs to be changed to run the 32-bit riscv OS

**Comment by eugene-tarassov** [comment]
Which OS? There is no Debian port for RISC-V 32-bit.

**Comment by Shuiliusheng** [comment]
I have compiled the linux (linux-stable) successfully with the riscv32-linux-gnu- , but I don't whether this vmlinux can be used and how to use it
