### ISSUE TITLE
rocketchip to vcu118

### ISSUE THREAD

**Issue by bocai-qd** [eugene-tarassov/vivado-risc-v#35]
I want to migrate to vcu118 and run Linux. Which project should I modify from, vcu1525 or vc707, but vcu1525 has no SD card module,thank you

**Comment by eugene-tarassov** [comment]
I think vc707 is better starting point.
Also, see [Issue 30: 16 or more RISC-V cores](https://github.com/eugene-tarassov/vivado-risc-v/issues/30) for some info on porting.
