### ISSUE TITLE
Vivado patch releases

### ISSUE THREAD

**Issue by jrrk** [eugene-tarassov/vivado-risc-v#36]
Thank you for making this splendid archive available.

If you use a Vivado patch release (e.g. 2020.1.1), then the board specific file (e.g. board/vc707/riscv-2020.1.1.tcl) is not found and the make fails. I was able to make progress by copying riscv-2020.1.1.tcl from risk-2020.1.tcl but I wonder if there is a more elegant way to do it automatically ?

**Comment by eugene-tarassov** [comment]
The recommended way to upgrade to a newer version of Vivado is to create project with older version, then open it with newer version of Vivado GUI, for example:
```
source ~/Xilinx/Vivado/2020.1/settings64.sh
make CONFIG=rocket64b2 BOARD=vc707 vivado-project

source ~/Xilinx/Vivado/2020.1.1/settings64.sh
make CONFIG=rocket64b2 BOARD=vc707 vivado-gui
```
Vivado will show a dialog box with "Automatically upgrade to the current version" option.
Selecting the option will start the upgrade process, which will upgrade and re-generate IPs in the design.

If upgraded project works OK, the new block design Tcl can be saved with this command in the Vivado Tcl Console:
'''
write_bd_tcl board/vc707/riscv-2020.1.1.tcl
'''

Optionally, you can edit the new Tcl to make it a bit more generic or more readable. In particular, replace Rocket64b2 with $rocket_module_name to make it compatible with other RISC-V configurations.

For a patch release, copying Tcl from older version also might work, but it depends on how much has changed between versions.
