### ISSUE TITLE
AC701 Support

### ISSUE THREAD

**Issue by AlexanderPuckhaber** [eugene-tarassov/vivado-risc-v#37]
Hi,

My research lab is still using some old AC701 boards, so I adapted some of your existing configurations (such as the nexys-a7-100t) to support it. 

I edited riscv-2020.2.tcl to setup the ddr3 MIG for the AC701. I imported the MIG configuration from files referenced in [this tutorial](https://www.xilinx.com/support/documentation/boards_and_kits/ac701/2014_4/xtp225-ac701-mig-c-2014-4.pdf). However, I don't know how to implement ethernet, so I removed it from the block diagram and device tree.

I have edited the constraints files `top.xdc`, `uart.xdc`, and `sdc.xdc` based on the ac701 manual.

My system boots your compiled linux images just fine; thanks for this great repo!

I was wondering if I could make [a pull request](https://github.com/eugene-tarassov/vivado-risc-v/compare/master...AlexanderPuckhaber:ac701) (once I clean up some of my changes). Having more examples of supported boards might help people implement new ones. 

Or, since I might not be able to test AC701 functionality every time your repository changes, I can keep my modifications as a fork.

**Comment by eugene-tarassov** [comment]
Yes, sure, pull request is good.
I don't have an AC701 board, I'll look into getting one.
Thanks!
