### ISSUE TITLE
How to connect Internet on VC707 board

### ISSUE THREAD

**Issue by xiongwu12345** [eugene-tarassov/vivado-risc-v#40]
I use the released vc707 bit and the ./mk-sd-cad command, the Linux can boot successfully.
And I use the internet cable to connect the board and the wired network port.
But when I try to connect to the Internet, as I use the command "sudo ping 182.61.200.6", it returns "the network is unreachable".
![image](https://user-images.githubusercontent.com/43496629/128990135-ef48fb3a-3d4d-4def-95cc-84fc32884df4.png)

And the IP address is as below:

![image](https://user-images.githubusercontent.com/43496629/128990049-ebf48748-abc7-4821-9e9a-ee7d12f7e3d8.png)

And I noticed that :
![image](https://user-images.githubusercontent.com/43496629/128990460-20845513-a1a4-4580-92b3-bb6548747b3e.png)

It seems that I need to change some MAC addresses and rebuild the bitstream. But what exactly should I do to connect the board to the Internet?

Thanks a lot!

**Comment by eugene-tarassov** [comment]
> But what exactly should I do to connect the board to the Internet?

You need to connect the board to 1Gb router using Ethernet cable and it should just work:

![ip-addr](https://user-images.githubusercontent.com/61023337/129119650-83d8988e-5f79-4643-a3f6-850b3f9984e4.PNG)

It looks like your cable is not connected or not working, because your screenshot shows NO-CARRIER status.

> It seems that I need to change some MAC addresses and rebuild the bitstream.

Only if you have multiple VC707 boards.

**Comment by xiongwu12345** [comment]
It solves my problem,thanks!

**Comment by xiaolingyi** [comment]
Hi, after some time, when I wanted to connect to the internet again, it suddenly showed NO-CARRIER status again. I did not change any file related to the Ethernet. And I changed to another brand new  VC707 board, the phenomenon was the same and I am sure the internet, as well as the Ethernet cable, is fine. 
So could you please provide any advice on how to test the ETHERNET devices on the board or how to solve this problem(for example, any config change)?
Thanks a lot!

**Comment by eugene-tarassov** [comment]
The board has SGMII interface to Ethernet PHY, so the design uses "1G/2.5G Ethernet PCS/PMA or SGMII" IP. The IP is proprietary and encrypted, so debug options are limited. I suggest to check the IPs Product Guide, it has plenty of info on how the IP should work, how to configure it, and how to create a test bench. You can also use Vivado to add ILA for the IP signals and check the waveforms.

I have VC707 board set up to run daily tests and have not seen any issues, I don't know what causes the NO-CARRIER status.
