### ISSUE TITLE
Unspecified I/O standard and Unconstrained Logic Port error

### ISSUE THREAD

**Issue by xiongwu12345** [eugene-tarassov/vivado-risc-v#41]
Hi, when I tried to generate the bitstream using this command "make CONFIG=rocket64b1 BOARD=vc707 bitstream",I used vivado2019.1 to run the project firstly，and find there is no corresponding vivado tcl file, so I renamed the 2020.1 version tcl file as 2019.1.tcl to run through the makefile. And  later  I encountered this error:
![image](https://user-images.githubusercontent.com/43496629/129054053-2ebd59f5-4585-4137-9831-ae7798efc3ba.png)

And In the vivado project, the error shows:
![image](https://user-images.githubusercontent.com/43496629/129054635-3940e9d2-8798-435d-8ded-a05130134879.png)
So I installed the vivado of 2021.1 and delete the vivado project file( all the files in directory workspace/rocket64b1 ). And I try to run again this command "make CONFIG=rocket64b1 BOARD=vc707 bitstream".But It still has the same error as above.
What does these error mean and how to fix them? And I am confused about if I didn't delete some file(generated by 2019.1 vivado) completely?
Thanks a lot!

**Comment by eugene-tarassov** [comment]
Vivado 2019.1 is not supported, and it looks like you are still using 2019.1 after installing 2021.1.
Did you run `source /opt/Xilinx/Vivado/2021.1/settings64.sh` to update environment variables?

**Comment by xiongwu12345** [comment]
Thanks, this problem is solved!
