### ISSUE TITLE
Add a custom rocc, linux boot fail 

### ISSUE THREAD

**Issue by xiongwu12345** [eugene-tarassov/vivado-risc-v#43]
Hi, I add my custom rocc to the rocket tile, and the bitstream was generated successfully. But the Linux boot step encounters some problems, as shown below. 

![d0262a5be304fcb67306aca554cd244](https://user-images.githubusercontent.com/43496629/129217393-248aed61-035d-49a9-b7ab-76dcd2cf6536.png)

So, do I need to modify some config and rebuild the Linux SD card?
If need, could you give me some advice?

**Comment by eugene-tarassov** [comment]
It looks like the RoCC makes the processor unstable and causes u-boot to crash with illegal instruction error. I think it is a problem with RoCC itself, but I'm not an expert in implementing Rocket coprocessors.

> So, do I need to modify some config and rebuild the Linux SD card?

No, I don't think there is anything to config in the software. U-boot should not have any dependencies on a custom RoCC.

**Comment by xiongwu12345** [comment]
>the RoCC makes the processor unstable

That is true, the timing constraints within the RoCC are not met. After I met the timing constrain, this error was solved naturally.
