### ISSUE TITLE
run baremetal or linux software

### ISSUE THREAD

**Issue by 12ff7a6** [eugene-tarassov/vivado-risc-v#50]
hello,

I have already deployed the rocket64b2gem on vc707 and can boot Linux. Then I want to test the Gemmini on vc707. I have built the Gemmini test binaries both for baremetal and linux according to the gemmini @ d4a2990. How can I run those test binaries on vc707?
much appreciated.

**Comment by gnodipac886** [comment]
@12ff7a6 did you ever happen to solve this issue?
