### ISSUE TITLE
Can DDR controller support two channel read/write?

### ISSUE THREAD

**Issue by xiongwu12345** [eugene-tarassov/vivado-risc-v#53]
Hi, I am a beginner at DDR4. The situation is that we developed a Custom RoCC processor with the Rocket and have deployed it in a VCU118 board. But we found the RoCC processor needs an internal DDR to store the intermediate data. Because BRAM can not store much data for our RoCC processor and the frequent data communication between Rocket and the  RoCC processor consumes too much cycle. So the Rocket needs a DDR to run a system and the RoCC processor needs a DDR as a big internal "buffer" to store its intermediate data during the processing stage. But there is only one DDR on the VCU118 board. So I wonder is that possible to divide this DDR into two smaller DDR so that half of it is used for Rocket and the other for the RoCC processor?

I found that the MIG only has one data port as listed below, so it seems that it's not possible to just instance one MIG. But I do not if instance two is possible two.

![image](https://user-images.githubusercontent.com/43496629/140613831-20feef01-82db-439c-a799-b52ab2883a24.png)

Thank you a lot!
Hope you have a nice weekend~

**Comment by eugene-tarassov** [comment]
On VCU118 board you can have up to 3 memory controllers: 2 DDR4 and 1 RLD3 - the board has 3 sets of memory chips.
You can also configure Rocket Chip SoC to have multiple memory buses and/or wider buses.
