### ISSUE TITLE
VCU118：I can't boot boom on VCU118

### ISSUE THREAD

**Issue by pig-pig-yang** [eugene-tarassov/vivado-risc-v#60]
prepared the bitstream according to the documentation and used 2020.1 Vivado to load the bitstream file. Secondly, the br-base-nodisk-flat file was generated according to the instructions. After loading the SD card, the following problems occurred in the RESET FPAG .

`INIT 
CMD0 
sd_cmd: timeout 
ERROR`
![image](https://user-images.githubusercontent.com/65580829/145747040-5ea86986-dd32-411c-9f01-85d81ee211ef.png)

**Comment by eugene-tarassov** [comment]
> Secondly, the br-base-nodisk-flat file was generated according to the instructions. 

It looks like some Chipyard stuff. You should ask about it on the [Chipyard site](https://github.com/ucb-bar/chipyard/issues).

This repo is about using RISC-V in Vivado Block Designs (aka Vivado IP Integrator). It has absolutely nothing to do with Chipyard.
