### ISSUE TITLE
Running Gemmini on Nexys-video failed

### ISSUE THREAD

**Issue by weihsi** [eugene-tarassov/vivado-risc-v#73]
hi, I'm trying to run a Gemmini on Nexys-video，because of the timing violations, I set clock_out_1 to 10MHz, and Linux cannot boot, I try a lot method, but they didn't work.
Is there some efficient way to solve this problem or if it is possible to run one rocket core with one Gemmini part on my board? Thanks!
I also want to ask for How to Debug using my own program(.elf) with XSDB, Thanks!

**Comment by eugene-tarassov** [comment]
When CPU clock speed is less then about 20MHz, you also need to reduce SD card clock speed. The card clock speed in set in the [board device tree](https://github.com/eugene-tarassov/vivado-risc-v/blob/master/board/nexys-video/bootrom.dts), look for max-frequency and change it to 25MHz instead of 50MHz.

> I also want to ask for How to Debug using my own program(.elf) with XSDB,

If you mean running bare-metal app, this is [RISC-V bare-metal "Hello World!" example](https://github.com/eugene-tarassov/vivado-risc-v/tree/master/bare-metal), which shows how to build a bootable .elf file. Such file can be debugged with XSDB (aka XSCT), see [Embedded Software Development (UG1400)](https://docs.xilinx.com/r/en-US/ug1400-vitis-embedded/Xilinx-Software-Command-Line-Tool?tocId=QZgoGihc9WgMzTcThhSxbw) for XSDB commands.

**Comment by weihsi** [comment]
I follow your step, and change max-frequency to 25MHz, but there is an ERROR:

```
invalid command name "CONFIG.CLKOUT2_REQUESTED_OUT_FREQ"
    while executing
"CONFIG.CLKOUT2_REQUESTED_OUT_FREQ {200.000} \ #200"
    (procedure "create_root_design" line 66)
    invoked from within
"create_root_design """
    (file "../../board/nexys-video/riscv-2021.1.tcl" line 802)

    while executing
"source ../../board/${vivado_board_name}/${block_design_tcl}"
    (file "../../vivado.tcl" line 78)
make: *** [Makefile:271: workspace/rocket64b1gem/vivado-nexys-video-riscv/timestamp.txt] Error 1
```
is there something else i need to change or adjust?

**Comment by weihsi** [comment]
After I change max-frequency to 25MHz, I try to boot linux on my board, but it's stuck at the following state, and I can't do anything except wait

```
[FAILED] Failed to start Network Time Synchronization.
See 'systemctl status systemd-timesyncd.service' for details.                           
[  OK  ] Stopped Network Time Synchronization.
         Starting Network Time Synchronization...                    
                               .
                               .
                               .
[FAILED] Failed to start Network Time Synchronization.
See 'systemctl status systemd-timesyncd.service' for details.                           
[  OK  ] Finished Coldplug All udev Devices.
```
I am wondering if there are some solutions or methods can solve my problem, Thanks!

**Comment by eugene-tarassov** [comment]
"Failed to start Network Time Synchronization" means the board cannot access network time servers. It is not a fatal error, the boot should continue after timeout.

I tried 10MHz clock on a Nexys board. It works OK after I changed max-frequency to 12.5MHz (25MHz appears too high). It boots very slowly at this clock speeds, but works OK eventually. I going to commit max-frequency 12.5MHz for Nexys boards.

Note that 10MHz clock is not normal, it is indication of a problems in Gemmini RTL. Hopefully, it will be fixed someday.

**Comment by weihsi** [comment]
As I change max frequency to 12.5MHz, it doesn't boot successfully, and still stuck at following error
```
Warning: fsck not present, so skipping root file system
Begin: Running /scripts/init-bottom ... Failed to send exit request: Resource temporarily unavailable
[ 1084.194130] systemd[1]: systemd-modules-load.service: Failed with result 'timeout'.
[FAILED] Failed to start Load Kernel Modules.
[ ***   1136.791760] random: crng init done
[FAILED] Failed to start Apply Kernel Variables.
[FAILED] Failed to start Flush Journal to Persistent Storage.

[  OK  ] Stopped Network Time Synchronization.
         Starting Network Time Synchronization...
[FAILED] Failed to start Network Time Synchronization.
See 'systemctl status systemd-timesyncd.service' for details.
[  OK  ] Finished Coldplug All udev Devices.
         Starting Helper to synchronize boot up for ifupdown...
[  OK  ] Stopped Network Time Synchronization.
         Starting Network Time Synchronization...
[FAILED] Failed to start Network Time Synchronization.
See 'systemctl status systemd-timesyncd.service' for details.
[  OK  ] Stopped Network Time Synchronization.
         Starting Network Time Synchronization...
[  OK  ] Finished Helper to synchronize boot up for ifupdown.
         Starting Raise network interfaces...
[FAILED] Failed to start Network Time Synchronization.
See 'systemctl status systemd-timesyncd.service' for details.
[  OK  ] Stopped Network Time Synchronization.
         Starting Network Time Synchronization...
[FAILED] Failed to start Network Time Synchronization.
See 'systemctl status systemd-timesyncd.service' for details.
```
So I change `/lib/systemd/system/systemd-timesyncd.service` `restart=always` ->`restart=no`, After about an hour of waiting, finally stuck at 
```
[FAILED] Failed to start OpenBSD Secure Shell server.
See 'systemctl status ssh.service' for details.                                        
[  OK  ] Stopped OpenBSD Secure Shell server.                                          
         Starting OpenBSD Secure Shell server...                                       
[  OK  ] Started OpenBSD Secure Shell server.
[  OK  ] Reached target Multi-User System.                                             
[  OK  ] Finished Remove Stale Onli�…ext4 Metadata Check Snapshots.
[  OK  ] Reached target Graphical Interface.                                           
         Starting Update UTMP about System Runlevel Changes...                         
[  OK  ] Finished Update UTMP about System Runlevel Changes.

```
Is there any changes or setup I need to do to let the system boot successfully, and I also want to ask how many time you spend to boot the debian from SD card

**Comment by eugene-tarassov** [comment]
> how many time you spend to boot the debian from SD card

Normally, Linux boot takes 3min on a Kintex/Virtex FPGA, 6min on an Artix FPGA.
At 10MHz, I measured 25min. And it should not show any "[FAILED]" messages.
You should look for the first error message - it is way before the Network Time Synchronization,
And it looks like your SD card is still not working properly.

> Is there any changes or setup I need to do to let the system boot successfully

You need to do a clean build to change frequencies, so remove (or backup) the workspace:
```
rm -rf workspace
```
Edit the device tree, change SD card frequency to `max-frequency = <12500000>;`:
```
vi board/nexys-video/bootrom.dts
```
Build bitstream:
```
source /opt/Xilinx/Vivado/2021.1/settings64.sh
make BOARD=nexys-video CONFIG=Rocket64b1gem ROCKET_FREQ_MHZ=10 bitstream
```
On the SD card, check DefaultTimeoutStartSec and DefaultTimeoutStopSec in /etc/systemd/system.conf.
For such slow CPU, you may need to increase timeouts to something like 600s.

**Comment by weihsi** [comment]
I rebuild my SD card with no error appears:
```
The partition table has been altered.
Calling ioctl() to re-read partition table.
Syncing disks.
fsck from util-linux 2.34
e2fsck 1.45.5 (07-Jan-2020)
Pass 1: Checking inodes, blocks, and sizes
Pass 2: Checking directory structure
Pass 3: Checking directory connectivity
Pass 4: Checking reference counts
Pass 5: Checking group summary information
rootfs: 17426/91968 files (0.0% non-contiguous), 205635/367360 blocks
resize2fs 1.45.5 (07-Jan-2020)
Resizing the filesystem on /dev/sdc2 to 30685696 (4k) blocks.
The filesystem on /dev/sdc2 is now 30685696 (4k) blocks long.
```
I follow your step and rebuild all of my environment, 
and I can boot successfully on CONFIG=Rocket64b1 ROCKET_FREQ_MHZ=50,
but I can't boot successfully on CONFIG=Rocket64b1gem ROCKET_FREQ_MHZ=10.
since the following fails:
```
Failed to wait for daemon to reply: Connection timed out
Begin: Running /scripts/init-bottom ... Failed to send exit request: Resource temporarily unavailable done.
[FAILED] Failed to start Apply Kernel Variables.
[FAILED] Failed to start Flush Journal to Persistent Storage.
[FAILED] Failed to start Network Time Synchronization.
```
I edit some system config:
/etc/security/limits.conf                   nproc = 65535  
/etc/systemd/system.conf               DefaultTimeoutStartSec and DefaultTimeoutStopSec = 600
but it still doesn't boot successfully and appears another Failed there.
```
Failed to wait for daemon to reply: Connection timed out
[FAILED] Failed to start Apply Kernel Variables.
[FAILED] Failed to start Flush Journal to Persistent Storage.
```
I am confused that is 'Gemmini' affect the whole project or not.
So, I want to ask do you add 'Gemmini' in your project or just only Rocket-core that can works OK?

**Comment by eugene-tarassov** [comment]
I don't have a regression test running for exact same configuration.
However, I have Rocket64b2gem on VC707 board, it runs Linux OK at 25MHz CPU clock.
I think 10MHz clock causes a timeout in Linux, but I'm not sure what timeout it is.

I have a lot of automated tests running on Nexys Video board, but without Gemmini.
Nexys boards are not good for experiments with Gemmini - too slow.

**Comment by weihsi** [comment]
After I change another FPGA borad instead nexys-video, finally I can using gemmini on FPGA normally, 
Thanks a lot.
