### ISSUE TITLE
BOOT failed!!!

### ISSUE THREAD

**Issue by codoor** [eugene-tarassov/vivado-risc-v#74]
I want to migrate to vcu118 and run Linux. I did this based the vc707 project and remove the enternet in the block design. I also modified the DDR ip.
But when I programmed the bitstream and then boot the linux from the sd card, the process of the boot stopped. Can you give me some suggestion for this. Does the network is necessary?
The serial port show as follow:
![image](https://user-images.githubusercontent.com/55735688/157452340-a09ece57-cc9c-4e65-b7c2-1331c9c97572.png)

**Comment by eugene-tarassov** [comment]
The network is not necessary to boot Linux.
The error message "unable to select a mode" means U-Boot cannot access SD card.
The message comes from sd_select_mode_and_width() function in U-Boot.

**Comment by codoor** [comment]
The function sd_select_mode_and_width() is seems to programm the parameter of bus. I'm not familiar with the u-boot, can you tell me what i should do to fix this.

**Comment by eugene-tarassov** [comment]
It fails to switch from 1-lane slow clock to 4-lane fast clock SD bus mode. So, it looks like the bus is not working: either wrong pins assignments, or timing constraints violations, or mechanical problem in the socket, etc.

These are common issues when porting a project to a new board. Usual ways to debug: double check constraints files, use integrated logic analyzer, use oscilloscope, use XSDB to step through the driver, etc.

**Comment by langccc** [comment]
> The function sd_select_mode_and_width() is seems to programm the parameter of bus. I'm not familiar with the u-boot, can you tell me what i should do to fix this.

Did you solve the problem,I got the same with you,I removed eth both in device tree and block design,and boot failed:
![image](https://user-images.githubusercontent.com/64479628/164472492-3ae7bef0-67d5-4125-868a-9b4146cee270.png)

**Comment by codoor** [comment]
I did not solve this problem. It guess the reason for this is a protocol mismatch, but i do not have enough time to modify the protocol.  So I try the chipyard's vcu118 bitstream and system boot(because that is use spi and this is use sdio), and it works. and  i also want to try to change to spi in the future.

> > The function sd_select_mode_and_width() is seems to programm the parameter of bus. I'm not familiar with the u-boot, can you tell me what i should do to fix this.
> 
> Did you solve the problem,I got the same with you,I removed eth both in device tree and block design,and boot failed: ![image](https://user-images.githubusercontent.com/64479628/164472492-3ae7bef0-67d5-4125-868a-9b4146cee270.png)

**Comment by langccc** [comment]
@codoor 
Thank you for reminding me，I remember I uesd to meet a error with  axi smartconnect ，So I changed axi smartconnect to axi interconnect ，and then it can access SD card ，but still hang in another place：
![image](https://user-images.githubusercontent.com/64479628/164644211-f135b927-4601-469a-9d9c-0027389b4975.png)

**Comment by Yuxin-Yu** [comment]
Hello @codoor , can I refer to your SD card configuration? I started Linux using VCU118, but couldn't detect the SD card. The error is as follows:
```
RISC-V 64, Boot ROM V3.6
Cannot access SD: Timeout
Cannot mount SD: Disk not ready
```
