### ISSUE TITLE
How to get a reserved-memory

### ISSUE THREAD

**Issue by flyxia624** [eugene-tarassov/vivado-risc-v#78]
I need to reserve some memory for the accelerator I added. According to a similar project, I modified the device tree in board/vcu1525/bootrom.dst by adding code like this: 
![image](https://user-images.githubusercontent.com/56917914/163460424-4a8f1d32-66c5-4c3a-a885-2cc83b54e75a.png)

I want to know if I'm right，Thank you.
BTW，I noticed that the vcu1525 block design has a peripheral device IIC. But the device tree does not contain this node，Does this IIC work without driver?

**Comment by eugene-tarassov** [comment]
> I want to know if I'm right

It looks OK to me.

> I noticed that the vcu1525 block design has a peripheral device IIC.

It is not used and not supported yet.

**Comment by flyxia624** [comment]
Thanks for your reply.I see
