### ISSUE TITLE
env: vivado: No such file or directory

### ISSUE THREAD

**Issue by KUEE1080** [eugene-tarassov/vivado-risc-v#79]
Hi, I am facing this issue while I am compiling FPGA bitstream. Has anyone experienced this kind of issues?? I am really waiting for help. Any reply will help me a lot. Thanks in advance.

My environment

Ubuntu 16.04 LTS
Vivado 2020.1

![image](https://user-images.githubusercontent.com/20737367/163808707-5879c108-0fe9-4c0b-930f-dfa2d2b2bfbf.png)

**if [ ! -e workspace/rocket64b2gem/vivado-genesys2-riscv ] ; then env XILINX_LOCAL_USER_DATA=no vivado -mode batch -nojournal -nolog -notrace -quiet -source workspace/rocket64b2gem/system-genesys2.tcl ; fi
env: ‘vivado’: No such file or directory
Makefile:271: recipe for target 'workspace/rocket64b2gem/vivado-genesys2-riscv/timestamp.txt' failed
make: *** [workspace/rocket64b2gem/vivado-genesys2-riscv/timestamp.txt] Error 127**

**Comment by KUEE1080** [comment]
Sorry. This was somewhat related to my server's permisson issue. Closing this issue.

**Comment by LeooLevinn** [comment]
Hi KUEE, I am facing the exact same thing.. How did you work things out plz?

**Comment by LeooLevinn** [comment]
Never  mind  :) I redo the repo in /home/<user> and it worked... Previously it was under /home
