### ISSUE TITLE
DDR3 frequency setting in Genesys2

### ISSUE THREAD

**Issue by Shuiliusheng** [eugene-tarassov/vivado-risc-v#86]
Hello, can I lower the DDR3 frequency so that it is lower than the CPU frequency? If so, how should I set it up?  I would like to configure it so that the cpu and mem speeds match the real scenario. Thank you very much!

**Comment by eugene-tarassov** [comment]
AFAIK, memory controller IP in Vivado cannot be configured to run at such low frequency.
Anyway, the memory controller configuration is documented in [UG586](https://docs.xilinx.com/v/u/en-US/ug586_7Series_MIS)
