### ISSUE TITLE
Add GPIO 

### ISSUE THREAD

**Issue by jack4041313** [eugene-tarassov/vivado-risc-v#98]
I want to add GPIO in block design,
I did:
1. make CONFIG=rocket64b2 BOARD=genesys2 vivado-gui
2. Add AXI GPIO in blkck design, validate and synthesize the design
3. Make sure GPIO_XILINX driver is available
4. Add GPIO to device tree, path vivado-risc-v/board/genesys2(myboard)/bootrom.dts
5. make CONFIG=rocket64b2 BOARD=genesys2 bitstream
6. Using Vivado GUI to program the FPGA flash memory

But when I turn on the FPGA and boot to linux, I can't see my GPIO in linux device tree (/proc/device-tree/io-bus)

Which step am I doing wrong?

**Comment by eugene-tarassov** [comment]
The file path `vivado-risc-v/board/genesys2(myboard)/bootrom.dts` is not right, it should not have `(myboard)` in it.
