### ISSUE TITLE
USB port

### ISSUE THREAD

**Issue by jack4041313** [eugene-tarassov/vivado-risc-v#99]
I want to add USB port on genesys2
Vivado axi usb 2.0 IP cannot be used because the pins do not match (input & output)
Do you have a suitable USB IP and driver for genesys2?

**Comment by eugene-tarassov** [comment]
> Vivado axi usb 2.0 IP cannot be used because the pins do not match (input & output)

Both Vivado and Genesys2 use ULPI interface. Pins appear to match.
I tried to add USB 2.0 IP to the block design - it worked fine.
However, the IP requires purchasing a license.
I'm not aware of a free USB 2.0 core.

**Comment by jack4041313** [comment]
Yes you are right
add USB 2.0 IP to the block design is worked fine
in vivado, USB 2.0 IP ULPI interface data section is separate
input data and output data is not the same pin
but on genesys2 ULPI interface,input data and output data is combined(inout)
this is my confusion point when writing constrain file

**Comment by eugene-tarassov** [comment]
> input data and output data is not the same pin
> but on genesys2 ULPI interface,input data and output data is combined(inout)

Vivado automatically adds IOBUFs in the design wrapper to convert I, O and T pins to IO pins when UPLI is made external.

**Comment by jack4041313** [comment]
Do you mean riscv_wrapper will combine these 3 pins automatically?
This is my block design, I have executed synthesis, but these three pins are not merged in my riscv_wrapper
![image](https://user-images.githubusercontent.com/81403859/184826350-86d7b91a-74a0-4e9c-bd40-a541acdc2af2.png)
![image](https://user-images.githubusercontent.com/81403859/184827462-4fbcc50b-bf34-4af6-8b7f-36fcbe344f64.png)

**Comment by jack4041313** [comment]
oh I should create a interface port 
Thank you for your response !
